### ISSUE TITLE
[suggestion] add streamlink-twitch-gui

### ISSUE THREAD

**Issue by freddiaN** [simoniz0r/spm#10]
Hello,  
it would be nice if you could add this application to the repository of spm. It's an electron app for easier use of streamlink for Twitch.tv streams.

Repository: https://github.com/streamlink/streamlink-twitch-gui  
Releases (only available as a .tar.gz as far as I know):  https://github.com/streamlink/streamlink-twitch-gui/releases

(I'm also in the "Discord Linux" Discordserver if you should have any questions)

**Comment by simoniz0r** [comment]
Done!  Run `spm -upd` to update your package lists, and you'll be able to install it. :D
