### ISSUE TITLE
Add Hexinator to SPM's list of AppImages

### ISSUE THREAD

**Issue by synalysis** [simoniz0r/spm#11]
https://hexinator.com/downloads/linux/Hexinator-x86_64.AppImage

**Comment by hub229ox** [comment]
hexinator costs $90  U$D and  **spm** is not an app-store to serve _get-rich-quick_ rip-off-schemes.

its an hexeditor like many others. KDE Okteta is free and better than hexinator.

**Comment by synalysis** [comment]
Wow, you really hit a weak spot here I have to admit!

I put hundreds of hours of work (of my life time) into that software, was working in evenings to fix issues or implement new features when others were sleeping. And you judge my work and me without knowing either the software or me.

If you actually believe that my software made or makes me rich you have no clue about how to get rich. 

Now this is the feedback of real users (which very rarely want a refund): https://www.synalysis.net/testimonials.html

If your life is miserable it doesn't help to drag others down. What could help is to be grateful for what you have and change your mental habits. Are you as good in encouraging people as you are in criticising them?

To have Hexinator on SPM had mainly the purpose to make it easier for people to install the software. Don't know why this is bothering someone who very likely also takes money for his work.
