### ISSUE TITLE
Make use of GitHub releases

### ISSUE THREAD

**Issue by TheAssassin** [simoniz0r/spm#3]
Uploading archives of any kind, but especially releases, is horribly inefficient. Since this project is on GitHub, I'd suggest you to make use of it as a platform for release management as well.

First of all, by requiring you to tag a specific Git commit, a pure user of Git can understand what commit was responsible for which release, which is a plus when trying to e.g. find a bug in a specific commit. Furthermore, by tagging releases, they're shown in a nice way to GitHub users. Also, GitHub users will be able to automatically download a freshly generated tarball of the latest sources.

If you really feel the need to (e.g. when your release tarball needs to have a structure different from your repository, or you want to include binaries), you can also upload any kind of file to a "release".

So, to avoid any inefficiency in the repository, and further improve your release workflow, please consider using GitHub releases.

**Comment by simoniz0r** [comment]
As it stands, the current version does use github release pages to get information for 68 of the AppImages.  When I created appimgman, most of the AppImages where being hosted on bintray, so it made the most sense to use that for the majority of the AppImages  Now that appimagehub is coming together well, I've started transitioning to using that as the main means of getting a list of AppImages.
You can see the progress [here](https://github.com/simoniz0r/appimgman/tree/spm). :D

**Comment by TheAssassin** [comment]
I was talking about the file `appimgman-0.2.7.tar.gz` in *your* repository. My suggestion is not related to AppImage topics, but general release management.

**Comment by simoniz0r** [comment]
That will be dealt in the rewrite that I'm working on [here](https://github.com/simoniz0r/appimgman/tree/spm).

**Comment by TheAssassin** [comment]
Ah, okay. I just noticed this, and thought I'd post that little proposal. If you're anyway going to change it, great. I'd suggest to leave this open until you've changed it.

**Comment by simoniz0r** [comment]
I've made enough progress to push the spm branch to master.  I still have a couple of changes to make for efficiency, but everything should be working as intended.

If you were using appimgman before, you can copy your installed config files from `~/.config/appimgman/installed/` to `~/.config/spm/appimginstalled/`, and spm will be able to detect them as being installed.
