### ISSUE TITLE
Best way to implement appimage support in linuxbrew

### ISSUE THREAD

**Issue by emanresusername** [simoniz0r/spm#9]
hoping to get some advice/ideas from similar projects on [this issue](https://github.com/Linuxbrew/homebrew-core/issues/4357)

(please excuse the copypasta 😅 thought this'd be the best combo of efficiency, related-github-repo-synnergy and visibility/discoverability for the relevant communities/contributers/etc)

**Comment by simoniz0r** [comment]
Please direct AppImage related questions to the [AppImage github pages](https://github.com/AppImage).  I recommend checking out [AppImageHub](https://github.com/AppImage/appimage.github.io/).
